# Site
name: "BOREDROOM NEWS"
description: "Bleeding Edge Thought Leadership"
meta_description: "News to Move Your Money"
logo: 'assets/images/BRN logo.png'
favicon: 'assets/images/BRN logo.png'
baseurl: '/'
title_image: 'assets/images/BRN logo.png'
google_analytics: 'UA-131122873-1'
disqus: 'boredroomnews'
mailchimp-list: 'https://boredroomnews.us7.list-manage.com/subscribe/post?u=26948d053fec052094653b9f3&amp;id=3d2b408f8d'

# Authors
authors:
  warren:
    name: warren
    display_name: Warren
    gravatar: b72c560fd9953bd4242bb23010d13d70 # md5 hash of warren@boredroomnews.com
    email: warren@boredroomnews.com
    web:
    twitter: https://twitter.com/boredroomnews
    description: "I am the Kwisatz Haderach of value investing"
  milton:
    name: milton
    display_name: Milton
    gravatar: 27647257edfb64779cae6bb521ae917f # md5 hash of milton@boredroomnews.com
    email: milton@boredroomnews.com
    web: 
    twitter: https://twitter.com/boredroomnews
    description: "Columbia University, Division of War Research '43-'45"
  sponsor:
    name: jack
    display_name: Jack
    gravatar: 9cb112e7848382de8a42e34765a101ee
    email: jack@boredroomnews.com
    web: 
    twitter: https://twitter.com/boredroomnews
    description: "Member, President Trump's Strategic and Policy Forum"
  sponsor:
    name: sponsor
    display_name: Sponsored post
    gravatar: c4da5d2f0407fdb224b0582401d8c556
    email: sponsor@boredroomnews.com
    web: 
    twitter: https://twitter.com/boredroomnews
    description: "This post is written by one of our fantastic sponsors; Boredroom News maintains plausible deniability for all content"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge