# Site
name: "BOREDROOM NEWS"
description: "Bleeding Edge Thought Leadership"
meta_description: "News to Move Your Money"
logo: 'assets/images/BRN logo.png'
favicon: 'assets/images/BRN logo.png'
baseurl: ''
google_analytics: 'UA-131122873-1'
disqus: 'boredroomnews'
mailchimp-list: 'https://boredroomnews.us7.list-manage.com/subscribe/post?u=26948d053fec052094653b9f3&amp;id=3d2b408f8d'

# Authors
authors:
  Paul:
    name: Paul
    display_name: Paul
    gravatar: 030dee8cbe0e34bfef91a89b707a640f # md5 hash of ethantschmidt@protonmail.com
    email: PaulAtreides@boredroomnews.com
    web:
    twitter: 
    description: "Muad'Dib."
  Duncan:
    name: Duncan
    display_name: Duncan
    gravatar: 030dee8cbe0e34bfef91a89b707a640f
    email: DuncanIdaho@boredroomnews.com
    web: 
    twitter: 
    description: "Ghola"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge