# Site
name: "BOREDROOM NEWS"
description: "Bleeding Edge Thought Leadership"
meta_description: "News to Move Your Money"
logo: 'assets/images/BRN logo.png'
favicon: 'assets/images/BRN logo.png'
baseurl: '/'
title_image: 'assets/images/BRN logo.png'
google_analytics: 'UA-131122873-1'
disqus: 'boredroomnews'
mailchimp-list: 'https://boredroomnews.us7.list-manage.com/subscribe/post?u=26948d053fec052094653b9f3&amp;id=3d2b408f8d'

# Authors
authors:
  Paul:
    name: Warren
    display_name: Warren
    gravatar: 030dee8cbe0e34bfef91a89b707a640f # md5 hash of ethantschmidt@protonmail.com
    email: warrenbuffet@boredroomnews.com
    web:
    twitter: 
    description: "I am the Kwisatz Haderach of value investing"
  Duncan:
    name: Milton
    display_name: Milton
    gravatar: 030dee8cbe0e34bfef91a89b707a640f
    email: miltonfriedman@boredroomnews.com
    web: 
    twitter: 
    description: "Division of War Research at Columbia University '43-'45"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge