# Site
name: "BORED ROOM NEWS"
description: "Bleeding Edge Thought Leadership"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/BRN logo.png'
favicon: 'assets/images/BRN logo.png'
baseurl: 'etschmidt.github.io/'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  sal:
    name: Paul
    display_name: Paul
    gravatar: 030dee8cbe0e34bfef91a89b707a640f # md5 hash of ethantschmidt@protonmail.com
    email: PaulAtreides@boredroomnews.com
    web:
    twitter: 
    description: "Muad'Dib."
  john:
    name: Duncan
    display_name: Duncan
    gravatar: 030dee8cbe0e34bfef91a89b707a640f
    email: DuncanIdaho@boredroomnews.com
    web: 
    twitter: 
    description: "Ghola"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge